### ISSUE TITLE
node 6.x: not working because utils-path is different ...

### ISSUE THREAD

**Issue by Apollon77** [soef/soef#2]
Running tr-064 in node 6.x crashes because of:

Error: Cannot find module '/opt/iobroker/node_modules/soef/../../lib/utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1086:23)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:14:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

The reason is the line:

        fns.adapter = require(__dirname + '/../../lib/utils').adapter;

because in node 6.x npm installs the modules differently.

I would init the "utils" in the main adapter ad then pass the adapter instance to the relevant method ...

Ingo F

**Comment by soef** [comment]
Did you install the Adapter using  --production --prefix "Path to ioBroker" Parameter? I am using node 6.9.2 and it runs. --
In version 0.1.44 I found a workaround. I think this will run in your Installation.

**Comment by Apollon77** [comment]
This happend after upgrading my installation from node 4.x to 6.x and using the "reinstall.sh" (the new version from github) ... but yes there the "--prefix "is missing ... hm ...

But in general as I found it I thought it is no good solution to make "inter-library references by path" ;-)
